kuka_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
<<<<<<< HEAD
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
=======
  # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
>>>>>>> f5d7d843c21079a5f73806d0365cee75353e490d
